const dummyCustomers = [
  {
    name: "Customer1",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer2",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer3",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer4",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer5",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer6",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer7",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer8",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer9",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer10",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer11",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer12",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  },
  {
    name: "Customer13",
    email: "customer@customer.pl",
    phone: null,
    vatNumber: "PL123123123",
    delivery_street: "Street 1",
    delivery_city: "City",
    delivery_country: "Country",
    delivery_postCode: null,
    billing_street: "Billing street 1",
    billing_city: "Billing city",
    billing_country: "Billing Country",
    billing_postCode: null,
    updatedAt: "2019-03-14T00:14:51.766Z",
    createdAt: "2019-03-14T00:14:51.766Z",
    deletable: true
  }
];

export default dummyCustomers;
